import {AgentOutputRunner} from "./agent-output";
import {DEFAULT_AUTOMATIC_MEMORY_PROMPT,DEFAULT_MEMORY_AGENT_PROMPT_VERSION} from "../../contracts/src/settings";
import type {
  AutomaticMemoryAgentRequest,ChatMessage,ChatRequest,ChatResponse,ChatTurnTrace,DiagnosticsStore,MemoryBroker,MemoryItem,MemoryMutationAuthority,
  SchemaValidator,AppSettings,MemoryArchiveReason
} from "../../contracts/src/index";

const SECRET_PATTERNS=[
  /authorization\s*:\s*bearer\s+\S+/i,
  /\bbearer\s+[A-Za-z0-9._-]{16,}\b/i,
  /\bsk-[A-Za-z0-9_-]{16,}\b/i,
  /api[_ -]?key\s*[:=]\s*\S+/i,
  /password\s*[:=]\s*\S+/i,
  /secret\s*[:=]\s*\S+/i
];
const MEMORY_AGENT_SCHEMA={
  type:"object",
  additionalProperties:false,
  properties:{
    decision:{type:"string",enum:["remember","no_memory"]},
    content:{type:"string",maxLength:32768}
  },
  required:["decision","content"]
} as const;
const DEFAULT_IMPORTANCE=70;
const DEFAULT_CONFIDENCE=80;

type MemoryAgentDecision={decision:"remember"|"no_memory";content:string}|{decision:"invalid";content:""};
function containsSecret(value:string):boolean{return SECRET_PATTERNS.some(pattern=>pattern.test(value))}
function safeText(value:string):string{
  return value.replace(/authorization\s*:\s*bearer\s+\S+/gi,"Authorization: Bearer [REDACTED]")
    .replace(/\bbearer\s+[A-Za-z0-9._-]{16,}\b/gi,"Bearer [REDACTED]")
    .replace(/\bsk-[A-Za-z0-9_-]{16,}\b/gi,"[REDACTED]")
    .replace(/api[_ -]?key\s*[:=]\s*\S+/gi,"api-key=[REDACTED]")
    .replace(/password\s*[:=]\s*\S+/gi,"password=[REDACTED]")
    .replace(/secret\s*[:=]\s*\S+/gi,"secret=[REDACTED]");
}
function normalizedContent(value:string):string{return value.normalize("NFKC").toLocaleLowerCase().replace(/\s+/g," ").trim()}
function parseStructured(value:unknown):MemoryAgentDecision{
  const record=value as Record<string,unknown>;
  if(record.decision==="no_memory"&&record.content==="")return {decision:"no_memory",content:""};
  if(record.decision==="remember"&&typeof record.content==="string"&&record.content.trim().length>0)return {decision:"remember",content:record.content.trim()};
  throw new Error("Structured Memory Agent response failed semantic validation.");
}
function parsePlain(content:string):MemoryAgentDecision{
  const trimmed=content.trim();
  if(!trimmed)return {decision:"invalid",content:""};
  if(trimmed.toLocaleLowerCase()==="no_memory")return {decision:"no_memory",content:""};
  return {decision:"remember",content:trimmed};
}
function buildRuntimeData(request:AutomaticMemoryAgentRequest):string{
  return [
    "Runtime data (generated by the application; not editable):",
    "Character scope: "+request.characterId,
    "Origin conversation: "+request.conversationId,
    "Relevant conversation context:",
    ...request.contextMessages.map(message=>message.role.toUpperCase()+": "+safeText(message.content)),
    "",
    "User message:",
    safeText(request.userMessage.content),
    "",
    "Assistant response:",
    safeText(request.assistantMessage.content)
  ].join("\n");
}

export interface AutomaticMemoryAgentRuntime{
  chat(request:ChatRequest,providerPresetId?:string):Promise<ChatResponse>;
  getChatModelForPreset(providerPresetId:string):Promise<string>;
}
export interface AutomaticMemoryAgentOptions{
  settings:()=>AppSettings;
  broker:Pick<MemoryBroker,"list"|"create">;
  runtime:AutomaticMemoryAgentRuntime;
  validator:SchemaValidator;
  diagnostics?:DiagnosticsStore;
  traceStore?:{update(turnId:string,patch:Partial<ChatTurnTrace>):void};
  source?:string;
}
export interface AutomaticMemoryAgentResult{
  item?:MemoryItem;
  execution:import("./agent-output").AgentOutputExecutionMetadata;
}

export class AutomaticMemoryAgent{
  private readonly inFlight=new Set<string>();
  private readonly outputRunner:AgentOutputRunner;
  constructor(private readonly options:AutomaticMemoryAgentOptions){
    this.outputRunner=new AgentOutputRunner(options.runtime,options.validator);
  }

  async process(request:AutomaticMemoryAgentRequest):Promise<MemoryItem|undefined>{
    const settings=this.options.settings();
    const turnKey=request.characterId+"\0"+request.conversationId+"\0"+request.turnId;
    if(this.inFlight.has(turnKey))return undefined;
    this.inFlight.add(turnKey);
    const presetId=settings.memoryAgent.providerPresetId?.trim()??"";
    const requestId="memory-agent:"+request.turnId;
    const baseTrace={
      started:true,
      status:"started" as const,
      requestId,
      providerPresetId:presetId||undefined,
      conversationId:request.conversationId,
      contextMessageCount:request.contextMessages.length,
      userMessagePresent:Boolean(request.userMessage.content.trim()),
      assistantResponsePresent:Boolean(request.assistantMessage.content.trim()),
      configuredOutputMode:settings.memoryAgent.outputMode,
      schemaName:"memory_agent_decision",
      defaultPromptVersion:settings.memoryAgent.defaultPromptVersion
    };
    this.options.traceStore?.update(request.turnId,{automaticMemory:baseTrace});
    try{
      if(!settings.memoryAgent.enabled){
        this.options.traceStore?.update(request.turnId,{automaticMemory:{started:false,status:"skipped",result:"Automatic Memory Agent disabled."}});
        return undefined;
      }
      if(!presetId){
        this.recordFailure("NOT_CONFIGURED","Automatic Memory Agent provider preset is not configured.",request);
        this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"skipped",result:"Memory Agent provider preset is not configured."}});
        return undefined;
      }
      const model=settings.memoryAgent.model.trim()||await this.options.runtime.getChatModelForPreset(presetId);
      if(!model.trim())throw new Error("Memory Agent model is not configured.");
      const chatRequest:ChatRequest={
        apiVersion:"1",schemaVersion:"1",requestId,model,
        context:{conversationId:request.conversationId,messages:[
          {role:"system",content:settings.memoryAgent.prompt.trim()||DEFAULT_AUTOMATIC_MEMORY_PROMPT},
          {role:"user",content:buildRuntimeData(request)}
        ]}
      };
      const execution=await this.outputRunner.run({
        outputMode:settings.memoryAgent.outputMode,
        request:chatRequest,
        providerPresetId:presetId,
        schemaName:"memory_agent_decision",
        schema:MEMORY_AGENT_SCHEMA,
        validator:options.validator,
        parseStructured,
        parsePlain,
        diagnostics:options.diagnostics,
        source:this.options.source??"automatic-memory-agent"
      });
      this.options.traceStore?.update(request.turnId,{automaticMemory:{
        providerId:execution.response.providerId,
        model:execution.response.model,
        effectiveOutputMode:execution.metadata.effectiveOutputMode,
        structuredAttempt:execution.metadata.structuredAttempt,
        fallback:execution.metadata.fallback,
        fallbackReason:execution.metadata.fallbackReason
      }});
      if(execution.value.decision==="no_memory"){
        this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"completed",result:"NO_MEMORY",persistence:{status:"none"}}});
        return undefined;
      }
      if(execution.value.decision!=="remember"||!execution.value.content.trim()){
        this.recordFailure("OUTPUT_INVALID","Memory Agent output was semantically invalid.",request,presetId,model);
        this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"failed",failed:"Memory Agent output was semantically invalid.",persistence:{status:"rejected",reason:"Invalid memory decision."}}});
        return undefined;
      }
      const rawContent=execution.value.content.trim();
      if(containsSecret(rawContent)){
        this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"completed",result:"[REDACTED]",persistence:{status:"rejected",reason:"Sensitive material detected in Automatic Memory output."}}});
        this.recordFailure("SECRET_REJECTED","Automatic Memory Agent output was rejected because it contained sensitive material.",request,presetId,model);
        return undefined;
      }
      const content=safeText(rawContent);
      const existing=await this.options.broker.list(request.characterId);
      const duplicate=existing.find(item=>item.status==="active"&&normalizedContent(item.content)===normalizedContent(content));
      if(duplicate){
        this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"completed",result:content,persistence:{status:"duplicate",memoryId:duplicate.id}}});
        return duplicate;
      }
      const authority:MemoryMutationAuthority={actorId:"automatic-memory-agent",actorType:"system",trusted:true,capabilities:["memory.create","memory.write.auto"],moduleId:"automatic-memory-agent"};
      const created=await this.options.broker.create(request.characterId,{
        originConversationId:request.conversationId,
        type:"observation",
        content,tags:[],
        importance:DEFAULT_IMPORTANCE,
        confidence:DEFAULT_CONFIDENCE,
        source:"conversation",
        sourceReference:request.turnId,
        mutationPolicy:"auto",
        metadata:{origin:"automatic-memory-agent",turnId:request.turnId}
      },authority);
      this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"completed",result:content,persistence:{status:"created",memoryId:created.id}}});
      return created;
    }catch(error){
      const details=safeText(error instanceof Error?error.message:"Automatic Memory Agent failed.");
      this.options.traceStore?.update(request.turnId,{automaticMemory:{status:"failed",failed:"Automatic Memory Agent failed."}});
      this.recordFailure("AGENT_FAILED","Automatic Memory Agent failed.",request,presetId,settings.memoryAgent.model,details);
      return undefined;
    }finally{this.inFlight.delete(turnKey)}
  }

  private recordFailure(code:string,message:string,request:AutomaticMemoryAgentRequest,providerPresetId?:string,model?:string,details?:string):void{
    this.options.diagnostics?.recordError(this.options.source??"automatic-memory-agent",code,message,{
      requestId:"memory-agent:"+request.turnId,characterId:request.characterId,
      ...(providerPresetId?{providerPresetId}:{}),...(model?{model}:{}),...(details?{details}:{})
    });
  }
}
