import type {
  AuditService,CharacterId,Clock,ConversationId,EventBus,EventPayloadMap,MemoryBroker,MemoryCreateInput,MemoryItem,MemoryItemId,MemoryMutationAuthority,
  MemorySearchQuery,MemoryStore,MemoryStoreState,MemoryStatus,MemoryType,MemoryUpdateInput,MemoryArchiveReason,SchemaValidator
} from "../../contracts/src/index";
import {MEMORY_API_VERSION,MEMORY_SCHEMA_VERSION,STANDARD_SCHEMAS,createEvent} from "../../contracts/src/index";

const MAX_CONTENT_LENGTH=32768;
const MAX_TAGS=32;
const MAX_TAG_LENGTH=64;
const MAX_SOURCE_REFERENCE_LENGTH=500;
const MAX_METADATA_KEYS=64;
const MAX_METADATA_BYTES=16384;
const MAX_QUERY_LENGTH=256;
const MAX_LIMIT=100;

export interface MemoryBrokerDependencies{
  store:MemoryStore;
  validator:SchemaValidator;
  audit:AuditService;
  events?:EventBus;
  clock?:Clock;
  source?:string;
  characterExists?:(characterId:CharacterId)=>Promise<boolean>;
}

function defaultClock():Clock{return {now:()=>new Date().toISOString()}}
function defaultIdFactory(prefix:string):()=>string{let sequence=0;return ()=>{sequence+=1;return prefix+"."+Date.now().toString(36)+"."+sequence.toString(36)}}
const idFactory=defaultIdFactory("memory");
function isRecord(value:unknown):value is Record<string,unknown>{return !!value&&typeof value==="object"&&!Array.isArray(value)}
function cloneMetadata(metadata:Record<string,unknown>):Record<string,unknown>{return {...metadata}}
function cloneItem(item:MemoryItem):MemoryItem{return {...item,tags:[...item.tags],metadata:cloneMetadata(item.metadata)}}
type MutableMemoryStoreState={apiVersion:"1";schemaVersion:string;characterId:CharacterId;items:MemoryItem[]};
function cloneState(state:MemoryStoreState):MutableMemoryStoreState{return {apiVersion:state.apiVersion,schemaVersion:state.schemaVersion,characterId:state.characterId,items:state.items.map(cloneItem)}}
function requireCharacterId(value:string):string{const result=value.trim();if(!result)throw new Error("Character id must not be empty.");if(result.length>200)throw new Error("Character id must not exceed 200 characters.");return result}
function requireConversationId(value:string):string{const result=value.trim();if(!result)throw new Error("Conversation id must not be empty.");if(result.length>200)throw new Error("Conversation id must not exceed 200 characters.");return result}
function requireMemoryId(value:string):string{const result=value.trim();if(!result)throw new Error("Memory id must not be empty.");if(result.length>200)throw new Error("Memory id must not exceed 200 characters.");return result}
function requireContent(value:string):string{if(typeof value!=="string"||value.trim().length===0)throw new Error("Memory content must be a non-empty string.");if(value.length>MAX_CONTENT_LENGTH)throw new Error("Memory content exceeds the v3 input limit.");return value}
function requireTags(tags:readonly string[]):string[]{if(!Array.isArray(tags)||tags.length>MAX_TAGS)throw new Error("Memory tags exceed the v1 input limit.");return tags.map(tag=>{if(typeof tag!=="string"||tag.trim().length===0)throw new Error("Memory tags must be non-empty strings.");if(tag.length>MAX_TAG_LENGTH)throw new Error("Memory tag exceeds the v1 input limit.");return tag})}
function requireScore(value:number,label:string):number{if(!Number.isInteger(value)||value<0||value>100)throw new Error(label+" must be an integer between 0 and 100.");return value}
function requireMetadata(metadata:Record<string,unknown>):Record<string,unknown>{if(!isRecord(metadata))throw new Error("Memory metadata must be an object.");if(Object.keys(metadata).length>MAX_METADATA_KEYS)throw new Error("Memory metadata exceeds the v1 key limit.");const serialized=JSON.stringify(metadata);if(serialized.length>MAX_METADATA_BYTES)throw new Error("Memory metadata exceeds the v1 size limit.");return cloneMetadata(metadata)}
function requireTimestamp(value:string,label:string):string{if(typeof value!=="string"||value.trim().length===0)throw new Error(label+" is required.");const trimmed=value.trim();if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/.test(trimmed))throw new Error(label+" must be an ISO-8601 timestamp.");if(!Number.isFinite(Date.parse(trimmed)))throw new Error(label+" must be a valid timestamp.");return trimmed}
function validateTemporalRange(validFrom:string|null,validUntil:string|null):void{if(validFrom!==null)requireTimestamp(validFrom,"validFrom");if(validUntil!==null)requireTimestamp(validUntil,"validUntil");if(validFrom!==null&&validUntil!==null&&Date.parse(validUntil)<Date.parse(validFrom))throw new Error("validUntil must not be earlier than validFrom.")}
function validateProvenance(source:MemoryItem["source"],sourceReference:string|null):void{if(["conversation","file","tool","model"].includes(source)&&(!sourceReference||sourceReference.trim().length===0))throw new Error("Memory sourceReference is required for "+source+" provenance.");if(sourceReference!==null&&sourceReference.length>MAX_SOURCE_REFERENCE_LENGTH)throw new Error("Memory sourceReference exceeds the v1 input limit.")}
function validateItemShape(item:MemoryItem,characterId:string,validator:SchemaValidator):void{
  if(item.characterId!==characterId)throw new Error("Memory item character scope mismatch.");
  const result=validator.validate(item,STANDARD_SCHEMAS["memory-item"]!);
  if(!result.valid)throw new Error("Memory item failed schema validation: "+result.errors.join("; "));
  requireMemoryId(item.id);requireContent(item.content);requireTags(item.tags);requireScore(item.importance,"importance");requireScore(item.confidence,"confidence");requireTimestamp(item.createdAt,"createdAt");requireTimestamp(item.updatedAt,"updatedAt");validateTemporalRange(item.validFrom,item.validUntil);validateProvenance(item.source,item.sourceReference);
  if(!["locked","suggest","auto"].includes(item.mutationPolicy))throw new Error("Invalid memory mutationPolicy.");
  if(!["active","superseded","archived"].includes(item.status))throw new Error("Invalid memory status.");
  if(item.archiveReason!==null&&!["manual","duplicate","superseded","other"].includes(item.archiveReason))throw new Error("Invalid memory archiveReason.");
  if(item.originConversationId!==null)requireConversationId(item.originConversationId);
  requireMetadata(item.metadata);
}
function validateState(state:MemoryStoreState,characterId:string,validator:SchemaValidator):void{if(state.apiVersion!==MEMORY_API_VERSION||state.schemaVersion!==MEMORY_SCHEMA_VERSION)throw new Error("Unsupported memory storage version.");if(state.characterId!==characterId)throw new Error("Memory storage character scope mismatch.");const ids=new Set<string>();for(const item of state.items){validateItemShape(item,characterId,validator);if(ids.has(item.id))throw new Error("Memory storage contains duplicate item ids.");ids.add(item.id)}}
function actorAllowed(item:MemoryItem,authority:MemoryMutationAuthority):void{if(authority.actorId.trim().length===0)throw new Error("Memory mutation actorId is required.");if(authority.actorType==="user")return;if(!authority.trusted)throw new Error("Memory mutation authority is not trusted.");if(item.mutationPolicy==="locked")throw new Error("Memory mutation denied by locked mutationPolicy.");if(item.mutationPolicy==="suggest"&&!authority.capabilities.includes("memory.write.suggest.apply"))throw new Error("Memory mutation denied by suggest mutationPolicy.");if(item.mutationPolicy==="auto"&&!authority.capabilities.includes("memory.write.auto"))throw new Error("Memory mutation denied by auto mutationPolicy.")}
function creationAllowed(item:MemoryItem,authority:MemoryMutationAuthority):void{if(authority.actorId.trim().length===0)throw new Error("Memory mutation actorId is required.");if(authority.actorType==="user")return;if(!authority.trusted||!authority.capabilities.includes("memory.create"))throw new Error("Memory creation denied by memory authority.");if(item.mutationPolicy==="auto"&&!authority.capabilities.includes("memory.write.auto"))throw new Error("Automatic memory creation requires memory.write.auto authority.")}
function compareItems(a:MemoryItem,b:MemoryItem):number{return b.importance-a.importance||b.confidence-a.confidence||b.updatedAt.localeCompare(a.updatedAt)||a.id.localeCompare(b.id)}function normalizeSearch(value:string):string{return value.normalize("NFKC").toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu," ").trim().replace(/\s+/g," ")}
function lexicalMatch(item:MemoryItem,query:string):boolean{
  const normalized=normalizeSearch(query);
  if(!normalized)return true;
  const queryTokens=normalized.split(" ").filter(Boolean);
  const itemTokens=normalizeSearch(item.content+" "+item.tags.join(" ")).split(" ").filter(Boolean);
  return queryTokens.some(queryToken=>itemTokens.some(itemToken=>itemToken===queryToken||(queryToken.length>=4&&(itemToken.startsWith(queryToken)||queryToken.startsWith(itemToken)))));
}

export class MemoryBrokerImpl implements MemoryBroker{
  private readonly clock:Clock;
  private readonly source:string;
  private readonly characterExists?: (characterId:CharacterId)=>Promise<boolean>;
  constructor(private readonly deps:MemoryBrokerDependencies){this.clock=deps.clock??defaultClock();this.source=deps.source??"memory-broker";this.characterExists=deps.characterExists}
  async get(characterId:CharacterId,memoryOrConversationId:MemoryItemId|ConversationId,memoryId?:MemoryItemId):Promise<MemoryItem|undefined>{
    const scope=await this.ensureCharacter(characterId);const id=requireMemoryId(memoryId??memoryOrConversationId);const state=await this.loadState(scope);const item=state.items.find(candidate=>candidate.id===id);return item?cloneItem(item):undefined;
  }
  async list(characterId:CharacterId):Promise<readonly MemoryItem[]>{const scope=await this.ensureCharacter(characterId);const state=await this.loadState(scope);return state.items.map(cloneItem)}
  async search(query:MemorySearchQuery):Promise<readonly MemoryItem[]>{
    const scope=await this.ensureCharacter(query.characterId);
    const schemaQuery={characterId:query.characterId,query:query.query,...(query.originConversationId!==undefined?{originConversationId:query.originConversationId}:{}),...(query.types?{types:query.types}:{}),...(query.tags?{tags:query.tags}:{}),...(query.status?{status:query.status}:{}),...(query.limit!==undefined?{limit:query.limit}:{})};
    const queryResult=this.deps.validator.validate(schemaQuery,STANDARD_SCHEMAS["memory-search-query"]!);if(!queryResult.valid)throw new Error("Memory search query failed schema validation: "+queryResult.errors.join("; "));if(query.query.length>MAX_QUERY_LENGTH)throw new Error("Memory search query exceeds the v3 input limit.");
    const limit=Math.min(query.limit??50,MAX_LIMIT);const state=await this.loadState(scope);const types=new Set<MemoryType>(query.types??[]);const requiredTags=(query.tags??[]).map(tag=>tag.toLocaleLowerCase());const status=query.status??"active";
    return state.items.filter(item=>item.status===status).filter(item=>types.size===0||types.has(item.type)).filter(item=>requiredTags.every(tag=>item.tags.some(itemTag=>itemTag.toLocaleLowerCase()===tag))).filter(item=>query.originConversationId===undefined||item.originConversationId===query.originConversationId).filter(item=>lexicalMatch(item,query.query)).sort(compareItems).slice(0,limit).map(cloneItem);
  }
  async create(characterId:CharacterId,input:MemoryCreateInput,authority:MemoryMutationAuthority):Promise<MemoryItem>{
    const scope=await this.ensureCharacter(characterId);const origin=input.originConversationId??(input.conversationId===undefined?null:requireConversationId(input.conversationId));const now=this.clock.now();
    const item:MemoryItem={id:requireMemoryId(input.id??idFactory()),characterId:scope,originConversationId:origin,type:input.type,content:requireContent(input.content),tags:requireTags(input.tags??[]),importance:requireScore(input.importance??50,"importance"),confidence:requireScore(input.confidence??50,"confidence"),createdAt:now,updatedAt:now,validFrom:input.validFrom===undefined?null:input.validFrom,validUntil:input.validUntil===undefined?null:input.validUntil,source:input.source,sourceReference:input.sourceReference===undefined?null:input.sourceReference,mutationPolicy:input.mutationPolicy??"locked",status:"active",archiveReason:null,metadata:requireMetadata(input.metadata??{})};
    validateItemShape(item,scope,this.deps.validator);creationAllowed(item,authority);const state=await this.loadState(scope);if(state.items.some(candidate=>candidate.id===item.id))throw new Error("Memory id already exists.");state.items.push(item);await this.persist(scope,state);await this.audit("create",scope,item.id,authority,"success");await this.publish("MemoryCreated",{characterId:scope,originConversationId:item.originConversationId??undefined,memoryId:item.id,status:item.status,updatedAt:item.updatedAt});return cloneItem(item);
  }
  async update(characterId:CharacterId,memoryOrConversationId:MemoryItemId|ConversationId,idOrInput:MemoryItemId|MemoryUpdateInput,inputOrAuthority:MemoryUpdateInput|MemoryMutationAuthority,maybeAuthority?:MemoryMutationAuthority):Promise<MemoryItem>{
    const legacy=typeof idOrInput==="string";const id=requireMemoryId(legacy?idOrInput as string:memoryOrConversationId);const updateInput=(legacy?inputOrAuthority: idOrInput) as MemoryUpdateInput;const authority=(legacy?maybeAuthority:inputOrAuthority) as MemoryMutationAuthority;const scope=await this.ensureCharacter(characterId);const state=await this.loadState(scope);const index=state.items.findIndex(candidate=>candidate.id===id);if(index<0)throw new Error("Memory item was not found.");const current=state.items[index]!;if(current.status!=="active")throw new Error("Only active memory items can be updated.");actorAllowed(current,authority);
    const next:MemoryItem={...current,type:updateInput.type===undefined?current.type:updateInput.type,content:updateInput.content===undefined?current.content:requireContent(updateInput.content),tags:updateInput.tags===undefined?[...current.tags]:requireTags(updateInput.tags),importance:updateInput.importance===undefined?current.importance:requireScore(updateInput.importance,"importance"),confidence:updateInput.confidence===undefined?current.confidence:requireScore(updateInput.confidence,"confidence"),validFrom:updateInput.validFrom===undefined?current.validFrom:updateInput.validFrom,validUntil:updateInput.validUntil===undefined?current.validUntil:updateInput.validUntil,source:updateInput.source===undefined?current.source:updateInput.source,sourceReference:updateInput.sourceReference===undefined?current.sourceReference:updateInput.sourceReference,mutationPolicy:updateInput.mutationPolicy===undefined?current.mutationPolicy:updateInput.mutationPolicy,metadata:updateInput.metadata===undefined?cloneMetadata(current.metadata):requireMetadata(updateInput.metadata),updatedAt:this.clock.now()};
    validateItemShape(next,scope,this.deps.validator);state.items[index]=next;await this.persist(scope,state);await this.audit("update",scope,id,authority,"success");await this.publish("MemoryUpdated",{characterId:scope,originConversationId:next.originConversationId??undefined,memoryId:id,status:next.status,updatedAt:next.updatedAt});return cloneItem(next);
  }
  async supersede(characterId:CharacterId,memoryOrConversationId:MemoryItemId|ConversationId,idOrInput:MemoryItemId|MemoryCreateInput,inputOrAuthority:MemoryCreateInput|MemoryMutationAuthority,maybeAuthority?:MemoryMutationAuthority):Promise<MemoryItem>{
    const legacy=typeof idOrInput==="string";const id=requireMemoryId(legacy?idOrInput as string:memoryOrConversationId);const createInput=(legacy?inputOrAuthority:idOrInput) as MemoryCreateInput;const authority=(legacy?maybeAuthority:inputOrAuthority) as MemoryMutationAuthority;const scope=await this.ensureCharacter(characterId);const state=await this.loadState(scope);const previous=state.items.find(item=>item.id===id);if(!previous)throw new Error("Memory item was not found.");if(previous.status!=="active")throw new Error("Only active memory items can be superseded.");actorAllowed(previous,authority);const now=this.clock.now();const replacement:MemoryItem={id:requireMemoryId(createInput.id??idFactory()),characterId:scope,originConversationId:createInput.originConversationId??(createInput.conversationId===undefined?previous.originConversationId:requireConversationId(createInput.conversationId)),type:createInput.type,content:requireContent(createInput.content),tags:requireTags(createInput.tags??[]),importance:requireScore(createInput.importance??previous.importance,"importance"),confidence:requireScore(createInput.confidence??previous.confidence,"confidence"),createdAt:now,updatedAt:now,validFrom:createInput.validFrom===undefined?previous.validFrom:createInput.validFrom,validUntil:createInput.validUntil===undefined?previous.validUntil:createInput.validUntil,source:createInput.source,sourceReference:createInput.sourceReference===undefined?null:createInput.sourceReference,mutationPolicy:createInput.mutationPolicy??previous.mutationPolicy,status:"active",archiveReason:null,metadata:requireMetadata(createInput.metadata??previous.metadata)};validateItemShape(replacement,scope,this.deps.validator);if(replacement.id===previous.id)throw new Error("Superseding memory must use a new memory id.");creationAllowed(replacement,authority);await this.deps.store.supersede(scope,previous.id,replacement);await this.audit("supersede",scope,replacement.id,authority,"success");await this.publish("MemorySuperseded",{characterId:scope,originConversationId:replacement.originConversationId??undefined,memoryId:replacement.id,previousMemoryId:previous.id,status:replacement.status,updatedAt:replacement.updatedAt});return cloneItem(replacement);
  }
  async archive(characterId:CharacterId,memoryId:MemoryItemId,authority:MemoryMutationAuthority,reason?:MemoryArchiveReason):Promise<MemoryItem>;
  async archive(characterId:CharacterId,conversationId:ConversationId,memoryId:MemoryItemId,authority:MemoryMutationAuthority,reason?:MemoryArchiveReason):Promise<MemoryItem>;
  async archive(characterId:CharacterId,memoryOrConversationId:MemoryItemId|ConversationId,memoryIdOrAuthority:MemoryItemId|MemoryMutationAuthority,maybeAuthority?:MemoryMutationAuthority,maybeReason?:MemoryArchiveReason):Promise<MemoryItem>{
    const legacy=typeof memoryIdOrAuthority==="string";const id=requireMemoryId(legacy?memoryIdOrAuthority as string:memoryOrConversationId);const authority=(legacy?maybeAuthority:memoryIdOrAuthority) as MemoryMutationAuthority;const reason=maybeReason??"manual";const scope=await this.ensureCharacter(characterId);const state=await this.loadState(scope);const index=state.items.findIndex(candidate=>candidate.id===id);if(index<0)throw new Error("Memory item was not found.");const current=state.items[index]!;if(current.status!=="active")throw new Error("Only active memory items can be archived.");actorAllowed(current,authority);const archived:MemoryItem={...current,status:"archived",archiveReason:reason,updatedAt:this.clock.now(),metadata:cloneMetadata(current.metadata)};validateItemShape(archived,scope,this.deps.validator);state.items[index]=archived;await this.persist(scope,state);await this.audit("archive",scope,id,authority,"success",reason);await this.publish("MemoryArchived",{characterId:scope,originConversationId:archived.originConversationId??undefined,memoryId:id,status:archived.status,updatedAt:archived.updatedAt,archiveReason:reason});return cloneItem(archived);
  }
  async restore(characterId:CharacterId,memoryId:MemoryItemId,authority:MemoryMutationAuthority):Promise<MemoryItem>{
    const scope=await this.ensureCharacter(characterId);const state=await this.loadState(scope);const index=state.items.findIndex(candidate=>candidate.id===requireMemoryId(memoryId));if(index<0)throw new Error("Memory item was not found.");const current=state.items[index]!;if(current.status!=="archived")throw new Error("Only archived memory items can be restored.");actorAllowed(current,authority);const restored:MemoryItem={...current,status:"active",archiveReason:null,updatedAt:this.clock.now(),metadata:cloneMetadata(current.metadata)};validateItemShape(restored,scope,this.deps.validator);state.items[index]=restored;await this.persist(scope,state);await this.audit("restore",scope,restored.id,authority,"success");await this.publish("MemoryRestored",{characterId:scope,originConversationId:restored.originConversationId??undefined,memoryId:restored.id,status:restored.status,updatedAt:restored.updatedAt});return cloneItem(restored);
  }
  async delete(characterId:CharacterId,memoryId:MemoryItemId,authority:MemoryMutationAuthority):Promise<void>{
    const scope=await this.ensureCharacter(characterId);const state=await this.loadState(scope);const id=requireMemoryId(memoryId);const index=state.items.findIndex(candidate=>candidate.id===id);if(index<0)throw new Error("Memory item was not found.");const current=state.items[index]!;actorAllowed(current,authority);state.items.splice(index,1);await this.persist(scope,state);await this.audit("delete",scope,id,authority,"success");await this.publish("MemoryDeleted",{characterId:scope,originConversationId:current.originConversationId??undefined,memoryId:id});
  }
  private async ensureCharacter(characterId:CharacterId):Promise<string>{const scope=requireCharacterId(characterId);if(this.characterExists&&!(await this.characterExists(scope)))throw new Error("Character was not found.");return scope}
  private async loadState(characterId:string):Promise<MutableMemoryStoreState>{const stored=await this.deps.store.load(characterId);if(!stored){const empty={apiVersion:MEMORY_API_VERSION,schemaVersion:MEMORY_SCHEMA_VERSION,characterId,items:[]};validateState(empty,characterId,this.deps.validator);return empty}validateState(stored,characterId,this.deps.validator);return cloneState(stored)}
  private async persist(characterId:string,state:MutableMemoryStoreState):Promise<void>{validateState(state,characterId,this.deps.validator);await this.deps.store.save(cloneState(state))}
  private async audit(operation:string,characterId:string,memoryId:string,authority:MemoryMutationAuthority,status:"success"|"denied"|"error",reason?:string):Promise<void>{await this.deps.audit.record({timestamp:this.clock.now(),actorId:authority.actorId,actorType:authority.actorType,module:authority.moduleId,action:"memory."+operation,resourceType:"resource",targetSummary:"character:"+characterId+"/memory:"+memoryId,argumentKeys:[],status,durationMs:0,allowed:status==="success",reason})}
  private async publish(type:"MemoryCreated",payload:EventPayloadMap["MemoryCreated"]):Promise<void>;
  private async publish(type:"MemoryUpdated",payload:EventPayloadMap["MemoryUpdated"]):Promise<void>;
  private async publish(type:"MemorySuperseded",payload:EventPayloadMap["MemorySuperseded"]):Promise<void>;
  private async publish(type:"MemoryArchived",payload:EventPayloadMap["MemoryArchived"]):Promise<void>;
  private async publish(type:"MemoryRestored",payload:EventPayloadMap["MemoryRestored"]):Promise<void>;
  private async publish(type:"MemoryDeleted",payload:EventPayloadMap["MemoryDeleted"]):Promise<void>;
  private async publish(type:"MemoryCreated"|"MemoryUpdated"|"MemorySuperseded"|"MemoryArchived"|"MemoryRestored"|"MemoryDeleted",payload:EventPayloadMap["MemoryCreated"]|EventPayloadMap["MemoryUpdated"]|EventPayloadMap["MemorySuperseded"]|EventPayloadMap["MemoryArchived"]|EventPayloadMap["MemoryRestored"]|EventPayloadMap["MemoryDeleted"]):Promise<void>{if(!this.deps.events)return;switch(type){case "MemoryCreated":await this.deps.events.publish(createEvent(type,payload as EventPayloadMap["MemoryCreated"],this.source,()=>this.clock.now()));break;case "MemoryUpdated":await this.deps.events.publish(createEvent(type,payload as EventPayloadMap["MemoryUpdated"],this.source,()=>this.clock.now()));break;case "MemorySuperseded":await this.deps.events.publish(createEvent(type,payload as EventPayloadMap["MemorySuperseded"],this.source,()=>this.clock.now()));break;case "MemoryArchived":await this.deps.events.publish(createEvent(type,payload as EventPayloadMap["MemoryArchived"],this.source,()=>this.clock.now()));break;case "MemoryRestored":await this.deps.events.publish(createEvent(type,payload as EventPayloadMap["MemoryRestored"],this.source,()=>this.clock.now()));break;case "MemoryDeleted":await this.deps.events.publish(createEvent(type,payload as EventPayloadMap["MemoryDeleted"],this.source,()=>this.clock.now()));break}}
}
