import type {DiagnosticsStore} from "../../contracts/src/index";
export type ModelRequestPriority="interactive"|"nova_cognition"|"maintenance";
export interface ModelRequestGovernorRequest<T>{id:string;priority:ModelRequestPriority;signal?:AbortSignal;retry?:boolean;execute:()=>Promise<T>}
export interface ModelRequestGovernorOptions{maxRequestsPerMinute:number|(()=>number);maxConcurrentRequests:number|(()=>number);backgroundRequestPriority?:number|(()=>number);retryDelayMs?:number|(()=>number);maxRetryDelayMs?:number|(()=>number);maxRetries?:number|(()=>number);maxRateLimitCooldownMs?:number|(()=>number);nowMs?:()=>number;sleep?:(ms:number,signal?:AbortSignal)=>Promise<void>;diagnostics?:DiagnosticsStore}
const bound=(v:number|undefined,d:number,min:number,max:number)=>Number.isInteger(v)?Math.min(max,Math.max(min,v)):d;
const resolve=(v:number|(()=>number)|undefined,d:number)=>typeof v==="function"?(()=>{try{return v()}catch{return d}})():v===undefined?d:v;
const abort=()=>{const e=new Error("Model request was aborted.");e.name="AbortError";return e};
const details=(e:unknown)=>{if(!e||typeof e!=="object")return undefined;const c=(e as any).chatError;return c&&typeof c==="object"&&c.details&&typeof c.details==="object"?c.details as Record<string,unknown>:undefined};
const isAbort=(e:unknown)=>Boolean(e&&typeof e==="object"&&"name" in e&&(e as any).name==="AbortError");
const retryAfter=(e:unknown)=>{const d=details(e);const v=(e as any)?.retryAfterMs??d?.retryAfterMs;return typeof v==="number"&&Number.isFinite(v)?Math.max(0,v):undefined};
const limited=(e:unknown)=>{const d=details(e);return d?.category==="rate_limit"||d?.httpStatus===429};
const retryable=(e:unknown)=>{if(isAbort(e)||limited(e))return !isAbort(e);const c=(e as any)?.chatError;return Boolean((e as any)?.retryable===true||c?.retryable===true)};
interface Entry{sequence:number;request:ModelRequestGovernorRequest<any>;resolve:(v:any)=>void;reject:(e:any)=>void}
export class ModelRequestGovernor{
 private readonly queue:Entry[]=[];private readonly started:number[]=[];private active=0;private seq=0;private timer:ReturnType<typeof setTimeout>|undefined;private cooldownUntil=0;
 constructor(private readonly options:ModelRequestGovernorOptions){}
 getSnapshot(){const n=this.now();this.prune(n);return{active:this.active,queued:this.queue.length,cooldownUntil:this.cooldownUntil,requestsInWindow:this.started.length,maxRequestsPerMinute:this.maxRpm(),maxConcurrentRequests:this.maxConcurrency()}}
 async run<T>(request:ModelRequestGovernorRequest<T>):Promise<T>{let attempt=0;for(;;){if(request.signal?.aborted)throw abort();try{return await this.enqueue(request)}catch(error){if(request.signal?.aborted||isAbort(error))throw error;const max=bound(resolve(this.options.maxRetries,2),2,0,5);if(request.retry===false||attempt>=max||!retryable(error))throw error;const after=retryAfter(error);const base=bound(resolve(this.options.retryDelayMs,1000),1000,50,60000);const cap=bound(resolve(this.options.maxRetryDelayMs,30000),30000,base,120000);const delay=Math.min(cap,after??Math.min(cap,base*Math.pow(2,attempt)));if(limited(error)){const c=bound(resolve(this.options.maxRateLimitCooldownMs,300000),300000,1000,600000);this.cooldownUntil=Math.max(this.cooldownUntil,this.now()+Math.min(c,delay));this.options.diagnostics?.recordError("model-request-governor","MODEL_REQUEST_RATE_LIMITED","Model request rate limited; entering cooldown.",{requestId:request.id,attempt:attempt+1,delayMs:delay,retryAfterMs:after??null})}attempt++;await this.sleep(delay,request.signal)}}}
 private enqueue<T>(r:ModelRequestGovernorRequest<T>){return new Promise<T>((resolvePromise,rejectPromise)=>{if(r.signal?.aborted){rejectPromise(abort());return}this.queue.push({sequence:this.seq++,request:r,resolve:resolvePromise,reject:rejectPromise});this.drain()})}
 private drain(){if(this.active>=this.maxConcurrency())return;let n=this.now();this.prune(n);if(this.cooldownUntil>n){this.schedule(this.cooldownUntil-n);return}if(this.started.length>=this.maxRpm()){this.schedule(Math.max(1,(this.started[0]??n)+60000-n));return}while(this.active<this.maxConcurrency()&&this.queue.length){n=this.now();this.prune(n);if(this.cooldownUntil>n){this.schedule(this.cooldownUntil-n);return}if(this.started.length>=this.maxRpm()){this.schedule(Math.max(1,(this.started[0]??n)+60000-n));return}this.queue.sort((a,b)=>this.priority(b.request.priority)-this.priority(a.request.priority)||a.sequence-b.sequence);const e=this.queue.shift()!;if(e.request.signal?.aborted){e.reject(abort());continue}this.started.push(n);this.active++;void e.request.execute().then(e.resolve,e.reject).finally(()=>{this.active--;this.drain()})}}
 private priority(p:ModelRequestPriority){return p==="interactive"?100:p==="nova_cognition"?75:bound(resolve(this.options.backgroundRequestPriority,10),10,0,50)}
 private schedule(ms:number){if(this.timer)return;this.timer=setTimeout(()=>{this.timer=undefined;this.drain()},Math.max(1,ms))}
 private prune(n:number){const cutoff=n-60000;while(this.started.length&&(this.started[0]??n)<=cutoff)this.started.shift()}
 private maxRpm(){return bound(resolve(this.options.maxRequestsPerMinute,30),30,1,120)}
 private maxConcurrency(){return bound(resolve(this.options.maxConcurrentRequests,2),2,1,8)}
 private now(){return this.options.nowMs?.()??Date.now()}
 private sleep(ms:number,signal?:AbortSignal){if(this.options.sleep)return this.options.sleep(ms,signal);return new Promise<void>((resolvePromise,rejectPromise)=>{if(signal?.aborted){rejectPromise(abort());return}const t=setTimeout(()=>{signal?.removeEventListener("abort",onAbort);resolvePromise()},ms);const onAbort=()=>{clearTimeout(t);rejectPromise(abort())};signal?.addEventListener("abort",onAbort,{once:true})})}
}
