import type {AgentDecision,Clock,DiagnosticsStore,StateStore} from "../../contracts/src/index";
export type NovaIntentStatus="active"|"completed";
export interface NovaIntent{id:string;type:string;description:string;status:NovaIntentStatus;priority:number;createdAt:string;updatedAt:string;dueAt:string|null;lastTriggeredAt:string|null}
export interface NovaGoal{id:string;description:string;status:"active"|"completed"|"failed";priority:number;createdAt:string;updatedAt:string}
export interface NovaPendingActivity{id:string;intentId:string;description:string;status:"pending";dueAt:string|null;priority:number}
export interface NovaAutonomyState{apiVersion:"1";schemaVersion:"1";characterId:string;currentFocus:string|null;activeIntentions:readonly NovaIntent[];activeGoals:readonly NovaGoal[];pendingActivities:readonly NovaPendingActivity[];lastMeaningfulInteraction:string|null;lastDecisionAt:string|null;nextRelevantDeadline:string|null}
export interface NovaAutonomyStore{load(characterId:string):Promise<NovaAutonomyState|undefined>;save(state:NovaAutonomyState):Promise<void>}
export class StateStoreNovaAutonomyStore implements NovaAutonomyStore{constructor(private readonly stateStore:StateStore){} load(characterId:string){return Promise.resolve(this.stateStore.get<NovaAutonomyState>("nova-autonomy:"+characterId))} save(state:NovaAutonomyState){return this.stateStore.set("nova-autonomy:"+state.characterId,JSON.parse(JSON.stringify(state)) as NovaAutonomyState)}}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T}
function validIso(v:string|null|undefined){return v===null||v===undefined||Number.isFinite(Date.parse(v))}
function priority(v:number){return Math.max(0,Math.min(100,Math.round(v)))}
export interface NovaAutonomyCoreOptions{store:NovaAutonomyStore;clock?:Clock;diagnostics?:DiagnosticsStore}
export class NovaAutonomyCore{
 private state?:NovaAutonomyState;private seq=0;private readonly clock:()=>string;
 constructor(private readonly options:NovaAutonomyCoreOptions){this.clock=options.clock?()=>options.clock!.now():()=>new Date().toISOString()}
 async initialize(characterId:string){const loaded=await this.options.store.load(characterId);this.state=loaded&&loaded.characterId===characterId?this.normalize(loaded,characterId):{apiVersion:"1",schemaVersion:"1",characterId,currentFocus:null,activeIntentions:[],activeGoals:[],pendingActivities:[],lastMeaningfulInteraction:null,lastDecisionAt:null,nextRelevantDeadline:null};this.recompute();await this.persist();return this.getState()}
 getState(){return clone(this.require())}
 async noteEvent(_trigger:string){this.state={...this.require(),lastMeaningfulInteraction:this.clock()};await this.persist();return this.getState()}
 async applyDecision(decision:AgentDecision){const state=this.require(),now=this.clock();let next={...state,lastDecisionAt:now};switch(decision.action){
  case "create_intent":{const dueAt=decision.intent.dueAt??null;if(!validIso(dueAt))throw new Error("Intent dueAt must be an ISO timestamp or null.");const intent:NovaIntent={id:"intent:"+state.characterId+":"+Date.now().toString(36)+":"+this.seq++,type:decision.intent.type.trim(),description:decision.intent.description.trim(),status:"active",priority:priority(decision.intent.priority),createdAt:now,updatedAt:now,dueAt,lastTriggeredAt:null};if(!intent.type||!intent.description)throw new Error("Intent type and description must not be empty.");next={...next,activeIntentions:[...state.activeIntentions,intent]};break}
  case "update_intent":{const i=state.activeIntentions.findIndex(item=>item.id===decision.intentId);if(i<0)throw new Error("Intent not found: "+decision.intentId);const current=state.activeIntentions[i]!,patch=decision.intent,dueAt=patch.dueAt===undefined?current.dueAt:patch.dueAt;if(!validIso(dueAt))throw new Error("Intent dueAt must be an ISO timestamp or null.");const updated={...current,...(patch.type===undefined?{}:{type:patch.type.trim()}),...(patch.description===undefined?{}:{description:patch.description.trim()}),...(patch.priority===undefined?{}:{priority:priority(patch.priority)}),dueAt,updatedAt:now};if(!updated.type||!updated.description)throw new Error("Intent type and description must not be empty.");const list=[...state.activeIntentions];list[i]=updated;next={...next,activeIntentions:list};break}
  case "complete_intent":next={...next,activeIntentions:state.activeIntentions.filter(item=>item.id!==decision.intentId)};break;
  default:break}
 this.state=next;this.recompute();await this.persist();return this.getState()}
 async markIntentTriggered(ids:readonly string[]){const set=new Set(ids),now=this.clock(),state=this.require();this.state={...state,activeIntentions:state.activeIntentions.map(item=>set.has(item.id)?{...item,lastTriggeredAt:now,updatedAt:now}:item)};this.recompute();await this.persist();return this.getState()}
 getDueIntentions(now=this.clock()){const nowMs=Date.parse(now);return this.require().activeIntentions.filter(item=>item.dueAt&&Date.parse(item.dueAt)<=nowMs&&(item.lastTriggeredAt===null||Date.parse(item.lastTriggeredAt)<Date.parse(item.dueAt!))).map(clone)}
 private normalize(state:NovaAutonomyState,characterId:string){return{apiVersion:"1" as const,schemaVersion:"1" as const,characterId,currentFocus:null,activeIntentions:(state.activeIntentions??[]).map(item=>({...item,status:"active" as const,dueAt:item.dueAt??null,lastTriggeredAt:item.lastTriggeredAt??null,priority:priority(item.priority)})),activeGoals:(state.activeGoals??[]).map(clone),pendingActivities:[],lastMeaningfulInteraction:state.lastMeaningfulInteraction??null,lastDecisionAt:state.lastDecisionAt??null,nextRelevantDeadline:null}}
 private recompute(){const s=this.require(),active=s.activeIntentions.filter(i=>i.status==="active"),focus=active.slice().sort((a,b)=>b.priority-a.priority||a.createdAt.localeCompare(b.createdAt))[0]?.description??null,pending=active.map(i=>({id:"activity:"+i.id,intentId:i.id,description:i.description,status:"pending" as const,dueAt:i.dueAt,priority:i.priority})),deadlines=active.filter(i=>i.dueAt&&!(i.lastTriggeredAt&&Date.parse(i.lastTriggeredAt)>=Date.parse(i.dueAt!))).map(i=>i.dueAt!).sort((a,b)=>Date.parse(a)-Date.parse(b));this.state={...s,currentFocus:focus,pendingActivities:pending,nextRelevantDeadline:deadlines[0]??null}}
 private async persist(){await this.options.store.save(this.require())}
 private require(){if(!this.state)throw new Error("Nova Autonomy is not initialized.");return this.state}
}