import {InMemoryAuditService} from "../../core/src";
import {InMemoryMemoryStore} from "../../host/memory/src";
import {createFoundationRuntime} from "../../runtime/bootstrap/src";
import {InMemoryCharacterStore} from "../../host/characters/src";
import {InMemoryConversationStore} from "../../host/conversations/src";
import type {MemoryStoreState,MemoryExtractionRequest} from "../../contracts/src";

function equal(actual:unknown,expected:unknown,label:string){if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(label+" expected "+String(expected)+" got "+String(actual))}
function ok(value:unknown,label:string){if(!value)throw new Error(label)}

async function main(){
  const characterStore=new InMemoryCharacterStore();
  const memoryStore=new InMemoryMemoryStore();
  const conversationStore=new InMemoryConversationStore();
  const runtime=await createFoundationRuntime({characterStore,memoryStore,conversationStore});
  await runtime.start();
  try{
    const nova=await runtime.getActiveCharacter();
    const novaConversation=await runtime.getActiveConversation(nova.id);
    const gm=await runtime.createCharacter({name:"GM"});
    const gmConversation=await runtime.getActiveConversation(gm.id);
    const created=await runtime.createMemory(nova.id,{
      id:"runtime.memory.1",conversationId:novaConversation.id,type:"experience",content:"Nova met the user at the lake.",tags:["lake","meeting"],
      importance:80,confidence:70,source:"conversation",sourceReference:"conversation/message-42",mutationPolicy:"locked"
    });
    const gmMemory=await runtime.createMemory(gm.id,{id:"runtime.memory.2",conversationId:gmConversation.id,type:"goal",content:"GM tracks separate goals.",source:"user",mutationPolicy:"suggest"});
    equal((await runtime.searchMemory({characterId:nova.id,conversationId:novaConversation.id,query:"lake"}))[0]?.id,created.id,"runtime search returns scoped memory");
    equal(await runtime.getMemory(gm.id,gmConversation.id,created.id),undefined,"runtime enforces character scope");
    await runtime.updateMemory(gm.id,gmConversation.id,gmMemory.id,{content:"GM tracks a separate goal."});
    const replacement=await runtime.supersedeMemory(nova.id,novaConversation.id,created.id,{
      id:"runtime.memory.3",conversationId:novaConversation.id,type:"experience",content:"Nova met the user in Munich.",tags:["meeting","munich"],
      importance:85,confidence:90,source:"user",mutationPolicy:"locked"
    });
    equal(replacement.status,"active","runtime supersede returns active replacement");
    equal((await runtime.getMemory(nova.id,novaConversation.id,created.id))?.status,"superseded","runtime retains historical memory");
    const reloaded=await createFoundationRuntime({characterStore,memoryStore,conversationStore});
    await reloaded.start();
    try{
      equal((await reloaded.getMemory(nova.id,novaConversation.id,replacement.id))?.content,"Nova met the user in Munich.","memory survives runtime restart");
      equal((await reloaded.searchMemory({characterId:gm.id,conversationId:gmConversation.id,query:"goal"})).length,1,"other character memory survives restart");
    }finally{await reloaded.stop()}
  }finally{await runtime.stop()}
  // A LONGMEMORY candidate is already generated by the same NovaTurn. This boundary must not call another LLM.
  const candidateRequest=(turnId:string,content:string,characterId:string,conversationId:string,signal=new AbortController().signal):MemoryExtractionRequest=>({
    apiVersion:"1",schemaVersion:"1",characterId,conversationId,turnId,model:"fake-cognitive-model",
    userMessage:{id:turnId+":user",role:"user",content:"Please remember this."},
    assistantMessage:{id:"nova-turn:"+turnId,role:"assistant",content,metadata:{source:"nova-life-longmemory-candidate",novaTurnLongMemoryCandidate:true,longMemoryAbortSignal:signal}},
    contextMessages:[]
  });
  const freshRuntime=await createFoundationRuntime({characterStore,memoryStore:new InMemoryMemoryStore(),conversationStore:new InMemoryConversationStore()});
  await freshRuntime.start();
  try{
    const freshNova=await freshRuntime.getActiveCharacter();
    const freshConversation=await freshRuntime.getActiveConversation(freshNova.id);
    const baseRequest=candidateRequest("longmemory-create","The user prefers train travel.",freshNova.id,freshConversation.id);
    const written=await freshRuntime.extractMemory(baseRequest);
    equal(written.length,1,"non-empty LONGMEMORY is persisted without a Memory Agent request");
    equal(written[0]?.content,"The user prefers train travel.","the exact candidate reaches Character Memory");
    equal(written[0]?.sourceReference,"longmemory-create","memory provenance refers to the originating turn");
    equal(written[0]?.originConversationId,freshConversation.id,"candidate remains character/conversation scoped");
    const duplicate=await freshRuntime.extractMemory({...baseRequest,turnId:"longmemory-duplicate"});
    equal(duplicate.length,0,"normalized active duplicate is rejected before another write");
    equal((await freshRuntime.listMemory(freshNova.id)).filter(item=>item.content==="The user prefers train travel.").length,1,"duplicate does not create a second MemoryItem");
    const cancelledController=new AbortController();cancelledController.abort();
    equal((await freshRuntime.extractMemory({...baseRequest,turnId:"longmemory-cancelled",assistantMessage:{...baseRequest.assistantMessage,id:"nova-turn:longmemory-cancelled",metadata:{...baseRequest.assistantMessage.metadata,longMemoryAbortSignal:cancelledController.signal}}})).length,0,"cancelled LONGMEMORY is ignored");
    equal((await freshRuntime.extractMemory({...baseRequest,turnId:"longmemory-secret",assistantMessage:{...baseRequest.assistantMessage,id:"nova-turn:longmemory-secret",content:"API key: sk-12345678901234567890"}})).length,0,"sensitive LONGMEMORY is rejected");
    const diagnostic=(await freshRuntime.diagnostics()).recentErrors;
    ok(diagnostic.some(entry=>entry.source==="nova-life-longmemory"&&entry.code==="DUPLICATE_SKIPPED"),"duplicate rejection is diagnosed");
    ok(diagnostic.some(entry=>entry.source==="nova-life-longmemory"&&entry.code==="SECRET_REJECTED"),"secret rejection is diagnosed");
  }finally{await freshRuntime.stop()}

  class FailingLongMemoryStore extends InMemoryMemoryStore{
    override async save(state:MemoryStoreState):Promise<void>{
      if(state.items.some(item=>item.metadata.origin==="nova-life-longmemory"))throw new Error("controlled memory storage failure");
      await super.save(state);
    }
  }
  const failingRuntime=await createFoundationRuntime({characterStore:new InMemoryCharacterStore(),memoryStore:new FailingLongMemoryStore(),conversationStore:new InMemoryConversationStore()});
  await failingRuntime.start();
  try{
    const character=await failingRuntime.getActiveCharacter();
    const conversation=await failingRuntime.getActiveConversation(character.id);
    const request=candidateRequest("longmemory-write-failure","A stable preference.",character.id,conversation.id);
    equal((await failingRuntime.extractMemory(request)).length,0,"MemoryBroker persistence failure is isolated from the completed turn");
    const diagnostics=(await failingRuntime.diagnostics()).recentErrors;
    ok(diagnostics.some(entry=>entry.source==="nova-life-longmemory"&&entry.code==="PERSIST_FAILED"),"memory write failure is diagnosed");
  }finally{await failingRuntime.stop()}
  ok(new InMemoryAuditService(),"audit architecture remains reusable");
  console.log("PASS Dynamic Memory runtime integration tests");
}
void main().catch(error=>{console.error(error);process.exitCode=1});
