fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(
                tauri_build::AppManifest::new().commands(&[
                    "get_host_diagnostics",
                    "set_runtime_diagnostics",
                    "get_runtime_diagnostics",
                    "save_credential",
                    "get_credential",
                    "delete_credential",
                    "credential_exists",
                    "get_provider_configuration",
                    "save_provider_configuration",
                    "delete_provider_configuration",
                    "get_characters",
                    "save_characters",
                    "get_core_book_entries",
                    "save_core_book_entries",
                    "get_memory_state",
                    "save_memory_state",
                    "supersede_memory",
                    "search_retrieval_index",
                    "rebuild_retrieval_index",
                    "rebuild_all_retrieval_index",
                    "upsert_retrieval_document",
                    "remove_retrieval_document",
                    "remove_retrieval_character",
                ]),
            ),
    )
    .expect("failed to build Tauri application metadata");
}
