import {DeterministicCognitiveStep,LLMCognitiveStep,MindRuntime,type CognitiveStep,type CognitiveStepContext} from "../../core/src";
import type {ChatRequest} from "../../contracts/src";
function equal(actual:unknown,expected:unknown,label:string){if(actual!==expected)throw new Error(label+" expected "+String(expected)+" got "+String(actual));}
function ok(value:unknown,label:string){if(!value)throw new Error(label);}
async function waitFor(predicate:()=>boolean,timeoutMs=1000):Promise<void>{const deadline=Date.now()+timeoutMs;while(!predicate()){if(Date.now()>=deadline)throw new Error("Timed out waiting for condition.");await new Promise(resolve=>setTimeout(resolve,5));}}
async function startRuntimeTest(){const runtime=new MindRuntime({cognitiveStep:new DeterministicCognitiveStep(),stepIntervalMs:2});await runtime.start();await waitFor(()=>runtime.getState().recentThoughts.length>=3);equal(runtime.getState().lifecycleState,"thinking","runtime stays thinking between cognitive steps");await runtime.stop();equal(runtime.getState().lifecycleState,"off","stop transitions runtime to off");}
async function sequentialStepsTest(){
 const seen:string[]=[];class Step implements CognitiveStep{running=0;maxRunning=0;async run(context:CognitiveStepContext){this.running+=1;this.maxRunning=Math.max(this.maxRunning,this.running);try{await new Promise(resolve=>setTimeout(resolve,4));const sequence=seen.length+1;seen.push(context.state.lastThought?.id??"none");return {id:"thought:"+sequence,timestamp:new Date().toISOString(),content:"step "+sequence,expression:"internal" as const};}finally{this.running-=1;}}}
 const step=new Step();const runtime=new MindRuntime({cognitiveStep:step,stepIntervalMs:2,recentThoughtLimit:50});await runtime.start();await waitFor(()=>runtime.getState().recentThoughts.length>=4);await runtime.stop();const state=runtime.getState();equal(step.maxRunning,1,"only one cognitive step runs at a time");equal(state.recentThoughts.length>=4,true,"recent thought history retains multiple thoughts");equal(seen[0],"none","first cognitive step sees initial state");equal(seen[1],"thought:1","second cognitive step sees first thought");equal(seen[2],"thought:2","third cognitive step sees second thought");
}
async function historyLimitTest(){const runtime=new MindRuntime({cognitiveStep:new DeterministicCognitiveStep(),stepIntervalMs:1,recentThoughtLimit:3});try{await runtime.start();await waitFor(()=>runtime.getState().recentThoughts.length===3);}finally{await runtime.stop();}const state=runtime.getState();equal(state.recentThoughts.length,3,"history is hard limited");const firstNumber=Number(state.recentThoughts[0]?.id.split(":").pop());const lastNumber=Number(state.lastThought?.id.split(":").pop());equal(firstNumber,lastNumber-2,"old thoughts are evicted from the bounded history");}
async function stopDuringActiveStepTest(){let started=0;const step:CognitiveStep={run:({signal})=>{started+=1;return new Promise((resolve,reject)=>{signal.addEventListener("abort",()=>reject(MindRuntime.createAbortError()),{once:true});});}};const runtime=new MindRuntime({cognitiveStep:step,stepIntervalMs:1});await runtime.start();await waitFor(()=>started===1);const stopPromise=runtime.stop();equal(runtime.getState().lifecycleState,"stopping","stop marks an active step as stopping");await stopPromise;equal(runtime.getState().lifecycleState,"off","runtime stops after an active cognitive step");equal(runtime.getState().recentThoughts.length,0,"aborted active step cannot publish a thought");}
async function restartAfterStopTest(){const step=new DeterministicCognitiveStep();const runtime=new MindRuntime({cognitiveStep:step,stepIntervalMs:1});await runtime.start();await waitFor(()=>runtime.getState().recentThoughts.length>=2);await runtime.stop();const firstStopCount=runtime.getState().recentThoughts.length;try{await runtime.start();await waitFor(()=>runtime.getState().recentThoughts.length>=3);}finally{await runtime.stop();}equal(firstStopCount>=2,true,"first stop completes after multiple thoughts");const lastId=runtime.getState().lastThought?.id??"";equal(lastId.startsWith("thought:deterministic:"),true,"restart continues the deterministic cognitive sequence");}
async function errorDoesNotStopLifeTest(){let count=0;const step:CognitiveStep={async run(){count+=1;if(count===1)throw new Error("cognitive failure");return {id:"thought:"+count,timestamp:new Date().toISOString(),content:"recovered",expression:"internal" as const};}};const errors:number[]=[];const runtime=new MindRuntime({cognitiveStep:step,stepIntervalMs:2,onError:()=>errors.push(count)});await runtime.start();await waitFor(()=>runtime.getState().lastThought?.content==="recovered");equal(errors.length,1,"cognitive error is reported");equal(count>=2,true,"runtime retries after error");equal(runtime.getState().lifecycleState,"thinking","life remains active after error");await runtime.stop();}
async function thoughtSubscriptionTest(){const runtime=new MindRuntime({cognitiveStep:new DeterministicCognitiveStep(),stepIntervalMs:2});const thoughts:string[]=[];const unsubscribe=runtime.subscribeThoughts(thought=>thoughts.push(thought.content));await runtime.start();await waitFor(()=>thoughts.length>=2);unsubscribe();const before=thoughts.length;await new Promise(resolve=>setTimeout(resolve,10));equal(thoughts.length,before,"unsubscribed observer stops receiving thoughts");await runtime.stop();}
async function llmCognitiveStepTest(){
 const calls:ChatRequest[]=[];const thought="A useful internal thought";
 const chatRuntime={chat:async(request:ChatRequest)=>{calls.push(request);return {apiVersion:"1" as const,schemaVersion:"1",requestId:request.requestId,conversationId:"conv-1",providerId:"fake.chat",model:request.model,message:{id:request.requestId+":assistant",role:"assistant" as const,content:JSON.stringify({thought})},finishReason:"stop" as const};},getActiveProviderPresetId:()=>"preset-1"};
 const step=new LLMCognitiveStep({runtime:chatRuntime,getActiveCharacter:async()=>({id:"char-1",name:"Nova",description:"Test character",createdAt:"now",updatedAt:"now",enabled:true}),getActiveConversation:async()=>({apiVersion:"1",schemaVersion:"2",id:"conv-1",characterId:"char-1",title:"Test",messages:[{id:"u1",role:"user",content:"Hello"}],createdAt:"now",updatedAt:"now"}),buildContext:async()=>({apiVersion:"1",schemaVersion:"1",characterId:"char-1",conversationId:"conv-1",messages:[{id:"cb1",role:"user",content:"Core book context"}],includedCandidates:[],omittedCandidates:[],budget:{availableContextTokens:1000,reservedOutputTokens:256,systemOverheadTokens:0,safetyMarginTokens:0},estimatedTokens:10}),getContextBudget:()=>({availableContextTokens:1000,reservedOutputTokens:256,systemOverheadTokens:0,safetyMarginTokens:0}),getActiveProviderPresetId:()=>"preset-1",getChatModel:()=> "unused",getChatModelForPreset:async()=> "fake-model"});
 const first=await step.run({state:{focus:"test",lastThought:null,lastThoughtAt:null,recentThoughts:[],lifecycleState:"thinking"},signal:new AbortController().signal});
 const firstCall=calls[0]!;equal(first.content,thought,"structured LLM output becomes Thought content");equal(first.expression,"internal","cognitive output is internal");equal(firstCall.metadata?.cognition,true,"cognition request is marked internal");equal(firstCall.generation?.responseFormat?.type,"json-schema","structured output is requested");equal(firstCall.context.messages.some(message=>message.content.includes("INTERNAL THOUGHT HISTORY")),true,"mind context includes thought history section");equal(firstCall.context.messages.some(message=>message.content==="Core book context"),true,"context engine output is included");
 const second=await step.run({state:{focus:"test",lastThought:first,lastThoughtAt:first.timestamp,recentThoughts:[first],lifecycleState:"thinking"},signal:new AbortController().signal});const secondCall=calls[1]!;const mindMessage=secondCall.context.messages.find(message=>message.content.includes("INTERNAL THOUGHT HISTORY"));ok(mindMessage?.content.includes(thought),"previous Thought is included in next cognition context");equal(second.expression,"internal","second cognitive step remains internal");
}
async function main(){await startRuntimeTest();await sequentialStepsTest();await historyLimitTest();await stopDuringActiveStepTest();await restartAfterStopTest();await errorDoesNotStopLifeTest();await thoughtSubscriptionTest();await llmCognitiveStepTest();console.log("PASS Mind Runtime + LLM cognitive tests");}
void main().catch(error=>{console.error(error);process.exitCode=1;});